CMIS Emulator: sff_8024_mem.MemorySpace Class Reference
sff_8024_mem.MemorySpace Class Reference
Public Member Functions
__init__ (self, bytes data)
int get_byte (self, int address)
bytes get_bytes (self, int start_address, int length)
str get_string (self, int start_address, int length)
__repr__ (self)
to_dict (self)
Protected Member Functions
_decode_field (self, name, start_addr, length, decoder=None)
Protected Attributes
_data
_fields
Detailed Description
Base class for a memory space. Subclasses define specific layouts.
Definition at line 95 of file sff_8024_mem.py.
Constructor & Destructor Documentation
__init__()
sff_8024_mem.MemorySpace.__init__ (self, bytes data)
Initializes the memory space with raw EEPROM data.
:param data: A bytes object representing the memory space.
Reimplemented in sff_8024_mem.SFF8024_BasePage00h, sff_8024_mem.SFF8472_DOMMemorySpace, sff_8024_mem.SFF8636_Page00h, sff_8024_mem.SFF8636_Page01h_CD, and sff_8024_mem.CMIS_Page00h.
Definition at line 99 of file sff_8024_mem.py.
Member Function Documentation
__repr__()
sff_8024_mem.MemorySpace.__repr__ (self)
Definition at line 134 of file sff_8024_mem.py.
_decode_field()
sff_8024_mem.MemorySpace._decode_field (self, name, start_addr, length, decoder = None) protected
Helper to decode and store a field.
Definition at line 124 of file sff_8024_mem.py.
References sff_8024_mem.MemorySpace._fields, and sff_8024_mem.MemorySpace.get_bytes().
get_byte()
int sff_8024_mem.MemorySpace.get_byte (self, int address)
Retrieves a single byte from the memory space.
Definition at line 107 of file sff_8024_mem.py.
References sff_8024_mem.MemorySpace._data.
get_bytes()
bytes sff_8024_mem.MemorySpace.get_bytes (self, int start_address, int length)
Retrieves a sequence of bytes from the memory space.
Definition at line 113 of file sff_8024_mem.py.
References sff_8024_mem.MemorySpace._data.
Referenced by sff_8024_mem.MemorySpace._decode_field(), and sff_8024_mem.MemorySpace.get_string().
get_string()
str sff_8024_mem.MemorySpace.get_string (self, int start_address, int length)
Retrieves a string from the memory space, stripping nulls.
Definition at line 120 of file sff_8024_mem.py.
References sff_8024_mem.MemorySpace.get_bytes().
to_dict()
sff_8024_mem.MemorySpace.to_dict (self)
Returns a dictionary representation of the decoded fields.
Definition at line 137 of file sff_8024_mem.py.
References sff_8024_mem.MemorySpace._fields.
Member Data Documentation
_data
sff_8024_mem.MemorySpace._data protected
Definition at line 104 of file sff_8024_mem.py.
Referenced by sff_8024_mem.MemorySpace.get_byte(), and sff_8024_mem.MemorySpace.get_bytes().
_fields
sff_8024_mem.MemorySpace._fields protected
Definition at line 105 of file sff_8024_mem.py.
Referenced by sff_8024_mem.MemorySpace._decode_field(), and sff_8024_mem.MemorySpace.to_dict().
The documentation for this class was generated from the following file:
sff_8024_mem.py