CMIS Emulator: src.capabilities.CapabilityManager Class Reference
src.capabilities.CapabilityManager Class Reference
Public Member Functions
__init__ (self)
Set[ModuleCapability] get_required_capabilities (self, ModuleType module_type)
Set[ModuleCapability] get_optional_capabilities (self, ModuleType module_type)
Dict[str, List[ModuleCapability]] validate_module (self, BaseModule module)
bool verify_capability (self, BaseModule module, ModuleCapability capability)
str describe_capability (self, ModuleCapability capability)
Detailed Description
Manages and validates module capabilities.
Tracks required and optional capabilities for different module types
and provides capability validation and verification.
Definition at line 17 of file capabilities.py.
Constructor & Destructor Documentation
__init__()
src.capabilities.CapabilityManager.__init__ (self)
Initialize capability requirements for different module types
Definition at line 24 of file capabilities.py.
Member Function Documentation
describe_capability()
str src.capabilities.CapabilityManager.describe_capability (self, ModuleCapability capability)
Get a human-readable description of a capability.
Args:
    capability: The capability to describe
Returns:
    Description of the capability
Definition at line 160 of file capabilities.py.
get_optional_capabilities()
Set[ModuleCapability] src.capabilities.CapabilityManager.get_optional_capabilities (self, ModuleType module_type)
Get the set of optional capabilities for a module type.
Args:
    module_type: The type of module
Returns:
    Set of optional capabilities
Definition at line 72 of file capabilities.py.
Referenced by src.capabilities.CapabilityManager.validate_module().
get_required_capabilities()
Set[ModuleCapability] src.capabilities.CapabilityManager.get_required_capabilities (self, ModuleType module_type)
Get the set of required capabilities for a module type.
Args:
    module_type: The type of module
Returns:
    Set of required capabilities
Definition at line 54 of file capabilities.py.
Referenced by src.capabilities.CapabilityManager.validate_module().
validate_module()
Dict[str, List[ModuleCapability]] src.capabilities.CapabilityManager.validate_module (self, BaseModule module)
Validate a module's capabilities against requirements.
Args:
    module: The module to validate
Returns:
    Dictionary containing:
    - 'missing_required': List of required capabilities that are missing
    - 'supported_optional': List of optional capabilities that are supported
    - 'unsupported_optional': List of optional capabilities that are not supported
Definition at line 90 of file capabilities.py.
References src.capabilities.CapabilityManager.get_optional_capabilities(), and src.capabilities.CapabilityManager.get_required_capabilities().
verify_capability()
bool src.capabilities.CapabilityManager.verify_capability (self, BaseModule module, ModuleCapability capability)
Verify if a specific capability is supported and functional.
Args:
    module: The module to verify
    capability: The capability to verify
Returns:
    True if the capability is supported and functional, False otherwise
Definition at line 119 of file capabilities.py.
The documentation for this class was generated from the following file:
src/capabilities.py