CMIS Emulator: tests.emulation.base.EmulatedModule Class Reference
tests.emulation.base.EmulatedModule Class Reference
Base class for emulated modules.
Public Member Functions
__init__ (self, ModuleConfig config)
Initialize emulated module.
bool is_present (self)
int get_identifier (self)
str get_vendor_name (self)
str get_part_number (self)
str get_serial_number (self)
str get_revision (self)
float get_temperature (self)
float get_voltage (self)
None set_temperature (self, float temperature)
None set_voltage (self, float voltage)
bool get_gpio_state (self, str signal)
None set_gpio_state (self, str signal, bool state)
int read_register (self, int address)
None write_register (self, int address, int value)
None add_memory_pages (self, List[int] pages)
None update_monitoring (self)
Public Attributes
config
memory_map
Protected Member Functions
None _initialize_memory_map (self)
None _handle_reset (self)
int _encode_temperature (self, float temp)
int _encode_voltage (self, float voltage)
int _encode_power (self, float power)
int _encode_bias (self, float bias)
None _write_string (self, int start_address, str string, int max_length)
Protected Attributes
_gpio_states
_temperature
_voltage
_tx_disable
_tx_fault
_rx_los
_tx_bias_ma
_tx_power_mw
_rx_power_mw
Detailed Description
Base class for emulated modules.
The EmulatedModule class provides the foundation for implementing module emulators. It handles:
Memory map management
GPIO signal states
Basic module status
Monitoring values
Configuration storage
Derived classes must implement the _initialize_memory_map() and update_monitoring() methods to provide module-specific functionality.
Example:
class SFFModule(EmulatedModule):
    def _initialize_memory_map(self):
        self.add_memory_pages([0xA0, 0xA2])
        self.memory_map.select_page(0xA0)
        self.memory_map.write_byte(0, self.config.identifier)
        # ... initialize other registers
    def update_monitoring(self):
        self.memory_map.select_page(0xA2)
        temp = self._encode_temperature(self._temperature)
        self.memory_map.write_word(96, temp)
        # ... update other monitoring values
Definition at line 290 of file base.py.
Constructor & Destructor Documentation
__init__()
tests.emulation.base.EmulatedModule.__init__ (self, ModuleConfig config)
Initialize emulated module.
Parameters
config Configuration parameters for the module
Sets up the base memory map and initializes all monitoring values to their defaults. Derived classes should call this before their own initialization.
Reimplemented in tests.emulation.cmis.CMISEmulatedModule, and tests.emulation.sff.SFFEmulatedModule.
Definition at line 322 of file base.py.
Member Function Documentation
_encode_bias()
int tests.emulation.base.EmulatedModule._encode_bias (self, float bias) protected
Encode bias current value for memory map
Definition at line 462 of file base.py.
_encode_power()
int tests.emulation.base.EmulatedModule._encode_power (self, float power) protected
Encode optical power value for memory map
Definition at line 455 of file base.py.
_encode_temperature()
int tests.emulation.base.EmulatedModule._encode_temperature (self, float temp) protected
Encode temperature value for memory map
Definition at line 441 of file base.py.
_encode_voltage()
int tests.emulation.base.EmulatedModule._encode_voltage (self, float voltage) protected
Encode voltage value for memory map
Definition at line 451 of file base.py.
_handle_reset()
None tests.emulation.base.EmulatedModule._handle_reset (self) protected
Handle module reset
Definition at line 430 of file base.py.
_initialize_memory_map()
None tests.emulation.base.EmulatedModule._initialize_memory_map (self) protected
Initialize the memory map with module-specific data
Reimplemented in tests.emulation.cmis.CMISEmulatedModule, and tests.emulation.sff.SFFEmulatedModule.
Definition at line 360 of file base.py.
_write_string()
None tests.emulation.base.EmulatedModule._write_string (self, int start_address, str string, int max_length) protected
Write a string to memory map with null termination
Definition at line 466 of file base.py.
add_memory_pages()
None tests.emulation.base.EmulatedModule.add_memory_pages (self, List[int] pages)
Add multiple memory pages
Definition at line 479 of file base.py.
get_gpio_state()
bool tests.emulation.base.EmulatedModule.get_gpio_state (self, str signal)
Get state of a GPIO signal
Definition at line 406 of file base.py.
Referenced by src.hardware.hal.HardwareInterface.get_interrupt_state(), and src.hardware.hal.HardwareInterface.module_present().
get_identifier()
int tests.emulation.base.EmulatedModule.get_identifier (self)
Get module identifier
Definition at line 368 of file base.py.
get_part_number()
str tests.emulation.base.EmulatedModule.get_part_number (self)
Get module part number
Definition at line 376 of file base.py.
get_revision()
str tests.emulation.base.EmulatedModule.get_revision (self)
Get module revision
Definition at line 384 of file base.py.
get_serial_number()
str tests.emulation.base.EmulatedModule.get_serial_number (self)
Get module serial number
Definition at line 380 of file base.py.
get_temperature()
float tests.emulation.base.EmulatedModule.get_temperature (self)
Get module temperature
Definition at line 388 of file base.py.
get_vendor_name()
str tests.emulation.base.EmulatedModule.get_vendor_name (self)
Get module vendor name
Definition at line 372 of file base.py.
get_voltage()
float tests.emulation.base.EmulatedModule.get_voltage (self)
Get module voltage
Definition at line 392 of file base.py.
is_present()
bool tests.emulation.base.EmulatedModule.is_present (self)
Check if module is present
Definition at line 364 of file base.py.
read_register()
int tests.emulation.base.EmulatedModule.read_register (self, int address)
Read from module's memory map
Definition at line 422 of file base.py.
set_gpio_state()
None tests.emulation.base.EmulatedModule.set_gpio_state (self, str signal, bool state)
Set state of a GPIO signal
Definition at line 412 of file base.py.
Referenced by src.hardware.hal.HardwareInterface.reset_module(), and src.hardware.hal.HardwareInterface.set_low_power_mode().
set_temperature()
None tests.emulation.base.EmulatedModule.set_temperature (self, float temperature)
Set module temperature
Reimplemented in tests.emulation.cmis.CMISEmulatedModule, and tests.emulation.sff.SFFEmulatedModule.
Definition at line 396 of file base.py.
set_voltage()
None tests.emulation.base.EmulatedModule.set_voltage (self, float voltage)
Set module voltage
Reimplemented in tests.emulation.cmis.CMISEmulatedModule, and tests.emulation.sff.SFFEmulatedModule.
Definition at line 401 of file base.py.
update_monitoring()
None tests.emulation.base.EmulatedModule.update_monitoring (self)
Update monitoring values in memory map
Reimplemented in tests.emulation.cmis.CMISEmulatedModule, and tests.emulation.sff.SFFEmulatedModule.
Definition at line 485 of file base.py.
write_register()
None tests.emulation.base.EmulatedModule.write_register (self, int address, int value)
Write to module's memory map
Definition at line 426 of file base.py.
Member Data Documentation
_gpio_states
tests.emulation.base.EmulatedModule._gpio_states protected
Definition at line 334 of file base.py.
_rx_los
tests.emulation.base.EmulatedModule._rx_los protected
Definition at line 346 of file base.py.
_rx_power_mw
tests.emulation.base.EmulatedModule._rx_power_mw protected
Definition at line 349 of file base.py.
_temperature
tests.emulation.base.EmulatedModule._temperature protected
Definition at line 340 of file base.py.
_tx_bias_ma
tests.emulation.base.EmulatedModule._tx_bias_ma protected
Definition at line 347 of file base.py.
_tx_disable
tests.emulation.base.EmulatedModule._tx_disable protected
Definition at line 344 of file base.py.
_tx_fault
tests.emulation.base.EmulatedModule._tx_fault protected
Definition at line 345 of file base.py.
_tx_power_mw
tests.emulation.base.EmulatedModule._tx_power_mw protected
Definition at line 348 of file base.py.
_voltage
tests.emulation.base.EmulatedModule._voltage protected
Definition at line 341 of file base.py.
config
tests.emulation.base.EmulatedModule.config
Definition at line 332 of file base.py.
memory_map
tests.emulation.base.EmulatedModule.memory_map
Definition at line 333 of file base.py.
The documentation for this class was generated from the following file:
tests/emulation/base.py