CMIS Emulator: basic_usage Namespace Reference
basic_usage Namespace Reference
Functions
None print_module_info (BaseModule module)
None print_module_status (BaseModule module)
None print_capability_info (BaseModule module, CapabilityManager capability_mgr)
None monitor_module (BaseModule module, float interval=1.0)
None main ()
Detailed Description
Example usage of the pluggable module management system.
This script demonstrates how to use the various components to manage
and monitor pluggable modules.
Function Documentation
main()
None basic_usage.main ()
Main function demonstrating module management
Definition at line 75 of file basic_usage.py.
References main(), monitor_module(), print_capability_info(), print_module_info(), and print_module_status().
Referenced by main().
monitor_module()
None basic_usage.monitor_module (BaseModule module, float interval = 1.0)
Continuously monitor a module's status
Definition at line 59 of file basic_usage.py.
Referenced by main().
print_capability_info()
None basic_usage.print_capability_info (BaseModule module, CapabilityManager capability_mgr)
Print capability information for a module
Definition at line 39 of file basic_usage.py.
Referenced by main().
print_module_info()
None basic_usage.print_module_info (BaseModule module)
Print detailed information about a module
Definition at line 14 of file basic_usage.py.
Referenced by main().
print_module_status()
None basic_usage.print_module_status (BaseModule module)
Print current module status
Definition at line 24 of file basic_usage.py.
Referenced by main().